### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by chasingkirkjufell** [navcoin/priverse-nft-marketplace#1]
1.  The Stats page, collections and active orders should be clickable and brings the user to a page listing all collections
2. Should probably also include total NFT counts
3. Overall, Stats page can provide a lot more information such as daily charts for various stats, average order prices.... take https://nonfungible.com/ for example.
4. Resources page, add more information such as "What is an NFT Collection?", "What is an NFT?", "Why are NFTs on Priverse private?, "Why should I care about privacy?" "What are schemes?" etc
5. I'd also like to see examples of NFT collections and NFTs with screenshots of what is input into the creation page and what does it look like when they are created. 
6. Explore page, I don't think it's necessary to have it pre-categorized. Change the tittle to "Explore Collections" and bring the user to a page with all collections. Add a filter to that page with the current categories would be better imo. 
7. What does the search bar do? I searched "Navcoin" which  is a collection but it doesn't do anything. 
8. Wallet button, clicking the wallet button should bring out the Chrome extension app on the top right and not create a new window. 
9. Wallet page, wallet tab, this page can have basic stats like balance etc. Take the wnav bridge as example of how metamask is connected and what's shown on the webpage.

**Comment by chasingkirkjufell** [comment]
10. Did you not want to include tokens for this page?

**Comment by sakdeniz** [comment]
1. Added link for list collections and active orders in Stats page.
2. Since the Priverse is an NFT marketplace, it does not index all NFT collections and NFTs. Only information about NFTs put up for sale and their collections is stored.
3. This is a feature that can be added in future versions. When there is enough data in the NFT marketplace, a work can be done about it.
4. I included the titles and contents you mentioned.
5. I added preview boxes to the NFT collection and NFT minting pages to give them an idea of what it would look like.
6. I added "All Collections" option to explorer dropdown menu so that it can show all nft collections regardless of any category. Some users may just want to browse NFTs in the category they are interested in. So I think it would be better to provide these users a quick option.
7. I activated the search box. You can search for expressions in the NFT name or description.
8. When you click on the wallet button, it is not possible to activate the wallet tab in the upper right. Instead, the window opens. It's the same with Metamask.
9. I have enabled NAV and xNAV balance to be shown on Marketplace wallet page. It will be active in the next wallet update (1.0.4).
10. If by token you mean Private Tokens, there is currently no purpose for them to be used on the NFT Marketplace.

Thanks!
